import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Catalog.module.scss";
import ClientLayout from "../components/Layouts/ClientLayout";
import CategoriesLayout from "../components/Layouts/CategoriesLayout";
import MainFeatured from "../components/Home/MainFeatured";
import Featured from "../components/Home/Featured";
import Card from "../components/Products/Card";
import Skeleton from "react-loading-skeleton";
import "react-loading-skeleton/dist/skeleton.css";
import usePhonesPaginate from "../utils/usePhonesPaginate";

// export async function getServerSideProps() {
//   const { phones } = await getAllPhones("brand_all", "offset_0,limit_5");

//   return {
//     props: {
//       phones: {
//         "/api/phones?query=brand_all&offset_0,limit_5": JSON.parse(
//           JSON.stringify(phones)
//         ),
//       },
//       phones: JSON.parse(JSON.stringify(phones)),
//     },
//   };
// }

// function fetchData(offset, limit) {
//   if (typeof window !== "undefined") {
//     const { data, error } = useSWR(
//       `/api/phones?query=brand_all,createdAt_$lte~${sessionStorage.getItem(
//         "sessionDate"
//       )}&options=offset_${offset},limit_${limit}`
//     );
//     return { data, error };
//   }
// }

export default function Home() {
  const { phonesData, endReached, isLoading, size, setSize, error, mutate } =
    usePhonesPaginate("/api/phones?query=brand_all", 8);

  const productCards = phonesData?.phones.map((phone) => (
    <Card
      key={phone._id}
      name={phone.name}
      image={phone.image.url}
      variations={phone.variations}
    />
  ));

  return (
    <div className={styles["catalog"]}>
      <Head>
        <title>Emphoneum | Shop Phones from Major Brands</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles["catalog__featured"]}>
        <div className={styles["featured"]}>
          <div className={styles["featured__main"]}>
            <MainFeatured />
          </div>
          <div className={styles["featured__other"]}>
            <Featured />
          </div>
          <div className={styles["featured__other"]}>
            <Featured />
          </div>
        </div>
      </div>
      <div className={styles["catalog__label-wrap"]}>
        <h2 className={styles["catalog__label"]}>Phones for You</h2>
      </div>
      <div className={styles["catalog__products"]}>
        {productCards ||
          [...Array(8)].map((_, i) => (
            <Skeleton key={i} className={styles["skeleton-card"]} />
          ))}
        {isLoading &&
          [...Array(8)].map((_, i) => (
            <Skeleton key={i} className={styles["skeleton-card"]} />
          ))}
      </div>
      <div className={styles["catalog__more-button-wrap"]}>
        {!endReached && (
          <button
            onClick={() => setSize(size + 1)}
            className={styles["catalog__more-button"]}
          >
            Load More
          </button>
        )}
      </div>
    </div>
  );
}

Home.getLayout = function getLayout(page) {
  return (
    <ClientLayout>
      <CategoriesLayout>{page}</CategoriesLayout>
    </ClientLayout>
  );
};
