import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import ClientLayout from "../components/Layouts/ClientLayout";
import CategoriesLayout from "../components/Layouts/CategoriesLayout";
import MainFeatured from "../components/Home/MainFeatured";
import Featured from "../components/Home/Featured";
import Card from "../components/Products/Card";
// import { getAllPhones } from "../lib/phone-queries";
import useSWR from "swr";
import Skeleton from "react-loading-skeleton";
import "react-loading-skeleton/dist/skeleton.css";

// export async function getServerSideProps() {
//   const { phones } = await getAllPhones("brand_all", "offset_0,limit_5");

//   return {
//     props: {
//       phones: {
//         "/api/phones?query=brand_all&offset_0,limit_5": JSON.parse(
//           JSON.stringify(phones)
//         ),
//       },
//       phones: JSON.parse(JSON.stringify(phones)),
//     },
//   };
// }

export default function Home() {
  const { data, error } = useSWR(
    "/api/phones?query=brand_all&options=offset_0,limit_8"
  );

  const productCards = data?.phones.map((phone) => (
    <Card
      key={phone._id}
      name={phone.name}
      image={phone.image.url}
      variations={phone.variations}
    />
  ));

  return (
    <div className={styles["l-home"]}>
      <Head>
        <title>Emphoneum | Shop Phones from Major Brands</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles["l-home__featured"]}>
        <div className={styles["c-featured"]}>
          <div className={styles["c-featured__main"]}>
            <MainFeatured />
          </div>
          <div className={styles["c-featured__other"]}>
            <Featured />
          </div>
          <div className={styles["c-featured__other"]}>
            <Featured />
          </div>
        </div>
      </div>
      <div className={styles["l-home__label"]}>
        <h2 className={styles["c-label"]}>Phones for You</h2>
      </div>
      <div className={styles["l-home__products"]}>
        {productCards || (
          <Skeleton
            containerClassName={styles["l-home__products"]}
            className={styles["skeleton-card"]}
            count={6}
          />
        )}
      </div>
    </div>
  );
}

Home.getLayout = function getLayout(page) {
  return (
    <ClientLayout>
      <CategoriesLayout>{page}</CategoriesLayout>
    </ClientLayout>
  );
};
